spring.application.name=backend

gh.url=http://graphhopper:8989


spring.datasource.url=jdbc:postgresql://db:5432/walk
spring.datasource.username=walk
spring.datasource.password=walk
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.spatial.dialect.postgis.PostgisPGDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true