spring.application.name=backend


gh.url=http://host.docker.internal:8989


spring.datasource.url=jdbc:postgresql://host.docker.internal:5433/walk
spring.datasource.username=walk
spring.datasource.password=walk
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.initialization-fail-timeout=0
spring.jpa.hibernate.ddl-auto=none
spring.main.lazy-initialization=true


springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.path=/api-docs
# ?????????? ?????????? ? UI
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha
